export const HOME_ROUTE = '/'
export const CALCULATE_ROUTE = '/'
export const MOVIE_ROUTE = '/films/'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const TELEGRAM_ROUTE = '/telegram-bot'